### ISSUE TITLE
[Suggestion] Mass generation of paper wallets for promotions

### ISSUE THREAD

**Issue by felixvd** [cantonbecker/bitcoinpaperwallet#17]
Hi,

I've been thinking that bulk generation of paper wallets would be very useful when printing wallets that are meant to be handed out.

Ideally, I am imagining an extra tab asking for the number of paper wallets to be generated (N) and a target folder. The output to the target folder should be:

* N two-page PDF files containing all the generated paper wallets, with numbered filenames
* A .csv of all the private keys
* A .csv of all the public keys

How hard would this be and how many Dogecoin in bounty would motivate you? :)

**Comment by asoltys** [comment]
Hey, just thought I'd chime in with a +1 for this.  Manually turning the pages around works fine when you're at home but I've been going to a print shop because I don't have a good colour printer.  They charge me double for running the pages through the printer twice.  If I could bring them a single PDF that had the two-up double-sided designs all laid out, that'd be rad.

I love the idea of having a csv of all the keys too.  Taking that a step further, you could use a BIP32 / BIP44 master key to derive the addresses and then it'd just be a matter of importing that single key into Mycelium or any wallet that supports it to sweep the wallets after some expiry date.

As for bulk cutting, I know my local hackspace has a laser cutter...  I might give it a try some time and I'll share the CAD file if I do.

**Comment by cantonbecker** [comment]
Hi,

I’d *love* to do PDF export, and I’ve looked into it, but it’s not practical/possible from Javascript. There are loads of PDF libraries out there for web services, but they generally require PHP and/or additional server side C++/compiled libraries.

I do like the idea of a master key/seed, but honestly I haven’t looked into the BIPs for it yet.

Most people with bulk needs are using bitaddress.org I believe which does a very good job of this. I think of my wallet as being more for small batches and individual wallets, especially since they require such patient cutting with scissors…

Thanks for the feedback!

- Canton

On Dec 15, 2015, at 3:34 PM, Adam Soltys <notifications@github.com> wrote:

> Hey, just thought I'd chime in with a +1 for this. Manually turning the pages around works fine when you're at home but I've been going to a print shop because I don't have a good colour printer. They charge me double for running the pages through the printer twice. If I could bring them a single PDF that had the two-up double-sided designs all laid out, that'd be rad.
> 
> I love the idea of having a csv of all the keys too. Taking that a step further, you could use a BIP32 / BIP44 master key to derive the addresses and then it'd just be a matter of importing that single key into Mycelium or any wallet that supports it to sweep the wallets after some expiry date.
> 
> As for bulk cutting, I know my local hackspace has a laser cutter... I might give it a try some time and I'll share the CAD file if I do.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------------------------------------------------
Canton Becker
canton@gmail.com • (505) 570-0635 • http://cantonbecker.com

**Comment by asoltys** [comment]
Hi Canton,

Fair enough, I thought about taking a stab at it with Javascript myself but just ended up using a command-line PDF utility to get the wallets printing 2-to-a-page and double-sided.  The bash script I used is here in case it's useful to anyone else:  https://github.com/asoltys/bitcoinpaperwallet_combiner

**Comment by cantonbecker** [comment]
> The bash script I used is here in case it's useful to anyone else: https://github.com/asoltys/bitcoinpaperwallet_combiner

pdftk FTW!

--------------------------------------------------------------------
Canton Becker
canton@gmail.com • (505) 570-0635 • http://cantonbecker.com
